"use client"
import { useTranslation } from '@/app/context/TranslationContext'
import FooterOne from '@/components/layout/footers/FooterOne'
import FooterTwo from '@/components/layout/footers/FooterTwo'
import Header1 from '@/components/layout/header/Header1'
import Link from 'next/link'
import React from 'react'

const cookierichtline = () => {

  const {translate} = useTranslation();

  return (
    <>
    <Header1 />
    <div className="container">
        <br /><br /><br /><br />
        <h2>{translate("Data protection")}</h2><br />
        <p>{translate("This website uses Google Analytics, a web analysis service provided by Google Inc. ('Google'). Google Analytics uses 'cookies', which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website is usually transferred to a Google server in the USA and stored there.")}</p><br />
        <p>{translate("However, if IP anonymisation is activated on this website, your IP address will be shortened beforehand by Google within member states of the European Union or in other contracting states to the Agreement on the European Economic Area. Only in exceptional cases will the full IP address be transmitted to a Google server in the USA and shortened there. On behalf of the operator of this website, Google will use this information to evaluate your use of the website, to compile reports on website activity and to provide the website operator with other services relating to website activity and internet usage. The IP address transmitted by your browser as part of Google Analytics will not be merged with other Google data. You can prevent cookies from being saved by setting your browser software accordingly; however, we would like to point out that in this case you may not be able to use all of the functions of this website to their full extent. You can also prevent Google from collecting the data generated by the cookie and relating to your use of the website (including your IP address) and from processing this data by downloading and installing the browser plug-in available under the following link.")}:</p>
        <Link href="http://tools.google.com/dlpage/gaoptout?hl=de.">http://tools.google.com/dlpage/gaoptout?hl=de.</Link><br/>
        <p>{translate("You can prevent Google Analytics from collecting data by adjusting the cookie settings for your website.")}</p>
        <p>{translate("Further information on terms of use and data protection can be found in the Google Analytics terms and conditions or in the Google Analytics overview. We would like to point out that Google Analytics has been extended on this website by the code 'gat._anonymizeIp();' in order to ensure anonymous collection of IP addresses (so-called IP masking).")}</p><br />
        <h1>{translate("Cookie Policy")}</h1><br />
        <p>{translate("With this Cookie Policy, the website operator informs the user of the website about the use of cookies or similar storage technologies (hereinafter 'cookies') on this website.")}</p><br />
        <p><b>{translate("What are cookies?")}</b></p><br />
        <p>{translate("Cookies are small text files that are stored by the web browser on the user's device to store certain information. The next time our website is accessed using the same device, the information stored in the cookie is sent back to our website ('first party cookie') or another website to which the cookie belongs ('third party cookie'). The information stored in the cookie and sent back enables the respective website to recognize that the user has already accessed and visited it using the web browser on their device. We use this information to be able to display the website to the user in the best possible way according to their preferences. However, only the cookie itself is identified on the device. Any further storage of personal data only occurs if the user gives us their express consent or if this storage is absolutely necessary in order to be able to use the service offered and accessed.")}</p><br />
        <p><b>{translate("Consent to the use of cookies")}</b></p><br />
        <p>{translate("Cookies that are not absolutely necessary to provide the services on this website are only used after consent has been given. By giving consent to the use of cookies on the basis of a notice provided by us on the website ('cookie banner'), the user agrees to the use of cookies. The user can adjust his cookie settings individually at any time, for example by activating or deactivating individual cookie categories. How the user can deactivate or delete cookies in general (including the absolutely necessary cookies) in his browser is described under the point 'Deactivation or deletion of all cookies'.")}</p><br />
        <p><b>{translate("Legal basis")}</b></p><br />
        <p>{translate("If the user has given consent to the use of cookies on the basis of a notice provided by us on the website (“cookie banner”), the legality of the data processing is governed by Art. 6 Paragraph 1 Clause 1 Letter a of GDPR. If no consent is requested, our legitimate interest (i.e. interest in the analysis, optimization and economic operation of this website and services) within the meaning of Art. 6 Paragraph 1 Clause 1 Letter f of GDPR represents the legal basis for the use of cookies.")}</p><br />
        <p><b>{translate("Functional cookies")}</b></p><br />
        <p>{translate("Functional cookies enable this website to save information provided, such as the user name or language selection, and to offer the user improved and personalized functions based on this. These cookies only collect and save anonymized information. No functional cookies are used on our website. The user can object to the use of functional cookies at any time by adjusting their cookie settings accordingly.")}</p><br /><p><b>Performance Cookies</b></p><br />
        <p>{translate("Performance cookies collect information about how our websites are used in order to improve their attractiveness, content and functionality. These cookies help us, for example, to determine whether and which subpages of our website are visited and which content users are particularly interested in. We record the number of accesses to a page, the number of subpages accessed, the time spent on our website, the order of the pages visited, which search terms led our users to us, the country, region and, if applicable, the city from which access is made, and the proportion of mobile devices that access our websites. The IP address of a computer transmitted for technical reasons is automatically anonymized and does not allow us to draw any conclusions about the individual user.")}</p>
        <br/>
        <br/>
        <br/>
        <br/>

    </div>
    <FooterTwo />
    </>
  )
}

export default cookierichtline